name: Deploy VMs

on:
  workflow_dispatch:
    inputs:
      vm_count:
        description: "Number of VMs for the first action"
        required: true
        default: "2"
      vm_count_1:
        description: "Number of VMs for the second action"
        required: true
        default: "3"

jobs:
  deploy_1:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenTofu
        run: |
          sudo snap install --classic opentofu
          tofu --version

      - name: Set up Kubernetes credentials
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          sudo mkdir -p /root/.kube
          echo "$KUBE_CONFIG" | sudo tee /root/.kube/config > /dev/null
          sudo chmod 644 /root/.kube/config

      - name: Initialize OpenTofu
        run: tofu init

      - name: Apply OpenTofu Configuration for Action 1
        env:
          VM_COUNT: ${{ github.event.inputs.vm_count_1 }}
        run: |
          tofu plan
          tofu apply -auto-approve

  deploy_2:
    runs-on: self-hosted
    needs: deploy_1  # Wait for deploy_1 to finish before starting this job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenTofu
        run: |
          sudo snap install --classic opentofu
          tofu --version

      - name: Set up Kubernetes credentials
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          sudo mkdir -p /root/.kube
          echo "$KUBE_CONFIG" | sudo tee /root/.kube/config > /dev/null
          sudo chmod 644 /root/.kube/config

      - name: Initialize OpenTofu
        run: tofu init

      - name: Apply OpenTofu Configuration for Action 2
        env:
          VM_COUNT: ${{ github.event.inputs.vm_count_2 }}
        run: |
          tofu plan
          tofu apply -auto-approve
