name: Deploy VM Worker

on:
  workflow_dispatch:
    inputs:
      var_file:
        description: 'Terraform var file'
        default: 'worker-main.tf'
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: k3s-config
          path: ./

      - name: Read config values
        id: read-config
        run: |
          MASTER_IP=$(cat master_ip.txt)
          K3S_TOKEN=$(cat k3s_token.txt)
          
          echo "MASTER_IP=$MASTER_IP" >> $GITHUB_ENV
          echo "K3S_TOKEN=$K3S_TOKEN" >> $GITHUB_ENV
          
          echo "Master IP: $MASTER_IP"
          echo "K3s Token: [SENSITIVE]"

      - name: Create tfvars file
        run: |
          cat > worker.auto.tfvars <<EOF
          master_ip = "${{ env.MASTER_IP }}"
          k3s_token = "${{ env.K3S_TOKEN }}"
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
