name: Deploy VMs

on:
  workflow_dispatch:
    inputs:
      vm_count:
        description: "Number of VMs"
        required: true
        default: "2"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenTofu
        run: |
          sudo snap install --classic opentofu
          tofu --version

      - name: Set up Kubernetes credentials
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}  # Κάνε use το GitHub Secret
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Initialize OpenTofu
        run: tofu init

      - name: Apply OpenTofu Configuration
        env:
          VM_COUNT: ${{ github.event.inputs.vm_count }}  # Pass the input to OpenTofu
        run: |
          tofu plan -var="vm_count=$VM_COUNT"
          tofu apply -auto-approve -var="vm_count=$VM_COUNT"

      - name: Upload tfstate as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: tofu-tfstate
          path: tofu.tfstate
