name: Deploy VMs

on:
  workflow_dispatch:
    inputs:
      vm_count:
        description: "Number of VMs"
        required: true
        default: "2"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenTofu
        run: |
          sudo snap install --classic opentofu
          tofu --version

      - name: Set up Kubernetes credentials
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}  # Κάνε use το GitHub Secret
        run: |
          sudo mkdir -p /root/.kube  # Δημιουργούμε το φάκελο για τον root χρήστη
          echo "$KUBE_CONFIG" | sudo tee /root/.kube/config > /dev/null  # Εγγράφουμε το config ως root
          sudo chmod 644 /root/.kube/config  # Ρυθμίζουμε τα δικαιώματα του αρχείου config

      - name: Initialize OpenTofu
        run: tofu init

      - name: Apply OpenTofu Configuration
        env:
          VM_COUNT: ${{ github.event.inputs.vm_count }}  # Pass the input to OpenTofu
        run: |
          tofu plan 
          tofu apply -auto-approve 

      - name: Upload tfstate as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: tofu-tfstate
          path: tofu.tfstate
