name: Deploy VMs (Workflow 1)
on:
  workflow_dispatch:
    inputs:
      var_file:
        description: "Variables file (within master directory)"
        required: true
        default: "variables.tfvars"
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install OpenTofu
        run: |
          sudo snap install --classic opentofu
          tofu --version
      - name: Set up Kubernetes credentials
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          sudo mkdir -p /root/.kube
          echo "$KUBE_CONFIG" | sudo tee /root/.kube/config > /dev/null
          sudo chmod 644 /root/.kube/config
      - name: Initialize OpenTofu
        run: |
          cd master/
          tofu init
      - name: Apply OpenTofu Configuration
        env:
          VAR_FILE: ${{ github.event.inputs.var_file }}
        run: |
          cd master/
          tofu plan -var-file=$VAR_FILE
          tofu apply -auto-approve -var-file=$VAR_FILE
      - name: Upload tfstate as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: tofu-tfstate
          path: master/terraform.tfstate
