name: Deploy VM Master

on:
  workflow_dispatch:
    inputs:
      var_file:
        description: 'Terraform var file'
        default: 'main.tf'
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get outputs
        id: tf-outputs
        run: |
          MASTER_IP=$(terraform output -raw master_ip)
          K3S_TOKEN=$(terraform output -raw k3s_token)
          
          echo "MASTER_IP=$MASTER_IP" >> $GITHUB_ENV
          echo "K3S_TOKEN=$K3S_TOKEN" >> $GITHUB_ENV
          
          # Αποθηκεύουμε τις τιμές σε αρχεία
          echo $MASTER_IP > master_ip.txt
          echo $K3S_TOKEN > k3s_token.txt
          
          # Εμφανίζουμε τις τιμές (χωρίς ευαίσθητα δεδομένα σε logs)
          echo "Master IP: $MASTER_IP"
          echo "K3s Token: [SENSITIVE]"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: k3s-config
          path: |
            master_ip.txt
            k3s_token.txt
